id = "ripple"
name = "Ripple"
description = "Ripple language support with LSP and Tree-sitter syntax highlighting"
version = "0.0.41"
schema_version = 1
authors = ["Dominic Gannaway <trueadm@users.noreply.github.com>"]
repository = "https://github.com/trueadm/ripple"

[grammars.ripple]
repository = "file://Z:/ripple/ripple"
rev = "2475a385f3e28050e554583706bf9f071397f0af"
path = "packages/tree-sitter-ripple"

[language_servers.ripple-language-server]
name = "Ripple Language Server"
languages = ["Ripple"]
