[package]
name = "tree-sitter"
description = "Ripple grammar for tree-sitter"
version = "0.0.1"
keywords = ["incremental", "parsing", "ripple"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/trueadm/ripple"
edition = "2021"
license = "MIT"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.22"

[build-dependencies]
cc = "1.0"
